# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextalkNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SDWebImage'
  # Pods for TextalkNews

  target 'TextalkNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextalkNewsUITests' do
    # Pods for testing
  end

end
